# Generated by Django 3.2.7 on 2023-05-28 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Урл страницы')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO keywords')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('menushow', models.BooleanField(default=False, verbose_name='Показывать в меню')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
