# Generated by Django 3.2.7 on 2023-05-28 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Урл страницы')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO keywords')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('photo', models.FileField(upload_to='news', verbose_name='Фото')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
